"""Render analysis results as markdown.

Written to be read on a phone: short lines, narrow tables, the important
findings at the top. Anyone reading only the first screen should still come
away with the things actually worth changing.
"""

from __future__ import annotations

from typing import Any

from ..model import COLOR_NAMES, Deck
from . import engine as engine_mod
from . import roles as roles_mod
from . import suggest as suggest_mod

BAR = "█"


def _bar(count: int, scale: int) -> str:
    if scale <= 0:
        return ""
    return BAR * max(0, round(count * 20 / scale))


def render_analysis(result: dict[str, Any]) -> str:
    deck = result["deck"]
    out: list[str] = []

    out.append(f"# {deck['name']}")
    out.append("")
    commanders = ", ".join(deck["commanders"]) or "—"
    identity = "/".join(deck["color_identity"]) or "colourless"
    out.append(f"**Commander:** {commanders}  ")
    out.append(f"**Identity:** {identity} · **Cards:** {deck['total_cards']} · **Format:** {deck['format']}  ")
    out.append(f"**Source:** {deck['url']}")
    out.append("")

    # --- what to look at first ------------------------------------------
    headline = result.get("headline") or []
    out.append("## What stands out")
    out.append("")
    if headline:
        for line in headline:
            out.append(f"- {line}")
    else:
        out.append("- Nothing structural to flag. The deck's shape looks sound.")
    out.append("")

    out.append(_intent_section(result.get("intent") or {}))
    out.append(_engine_section(result.get("engine") or {}))
    out.append(_legality_section(result["legality"]))
    out.append(_mana_section(result["mana"]))
    out.append(_curve_section(result["curve"]))
    out.append(_roles_section(result["roles"]))
    out.append(_edhrec_section(result["edhrec"]))
    out.append(_combo_section(result["combos"]))
    out.append(_bracket_section(result["bracket"]))
    out.append(_price_section(result["price"]))

    out.append("---")
    out.append("")
    out.append(
        "_Generated by `mtg deck analyze`. Suggestions are advisory — apply what you "
        "agree with in Archidekt yourself._"
    )
    return "\n".join(out) + "\n"


def _intent_section(data: dict[str, Any]) -> str:
    """What Nicolas has declared the deck to be — printed so every judgement
    below can be checked against it."""
    if not data:
        return ""
    out = ["## Intent (declared)", ""]
    if data.get("archetype"):
        out.append(f"**{data['archetype']}**")
        out.append("")
    line_bits = []
    if data.get("tribe"):
        line_bits.append(f"tribe: {data['tribe']}")
    if data.get("commander_role"):
        line_bits.append(f"commander is the {', '.join(data['commander_role'])}")
    if data.get("power_bracket"):
        line_bits.append(f"target bracket {data['power_bracket']}")
    if data.get("budget_per_card") is not None:
        line_bits.append(f"budget ${data['budget_per_card']:g}/card")
    if line_bits:
        out.append(" · ".join(line_bits))
        out.append("")
    if data.get("win_conditions"):
        out.append("Wins by: " + "; ".join(data["win_conditions"]))
        out.append("")
    if data.get("core_cards"):
        out.append(
            f"Untouchable: {', '.join(data['core_cards'])} — the tool will not "
            "suggest cutting these."
        )
        out.append("")
    if data.get("meta_notes"):
        out.append(f"Table notes: {data['meta_notes']}")
        out.append("")
    return "\n".join(out)


def _sorted_clusters(data: dict[str, Any]) -> list[tuple[str, int]]:
    """Commander-wanted clusters first, then by size — the plan before the plumbing."""
    clusters = data.get("clusters") or {}
    wants = set(data.get("commander_wants") or [])
    return sorted(
        clusters.items(), key=lambda kv: (kv[0] not in wants, -kv[1], kv[0])
    )


def _tribe_line(data: dict[str, Any]) -> str | None:
    census = data.get("tribe_census") or {}
    if not census:
        return None
    parts = [f"{census['true_type']} true {census['tribe']}s"]
    if census.get("changelings"):
        parts.append(f"{census['changelings']} changelings")
    if census.get("conditional_copies"):
        parts.append(
            f"{census['conditional_copies']} copy effects that become "
            f"{census['tribe']}s when they copy one"
        )
    return f"**Tribe:** {' + '.join(parts)}"


def _engine_section(data: dict[str, Any]) -> str:
    """What the deck is built around — read this before judging any card."""
    if not data:
        return ""
    out = ["## What this deck does", ""]
    out.append(f"**{data.get('archetype', 'no dominant theme')}**")
    out.append("")

    tribe_line = _tribe_line(data)
    if tribe_line:
        out.append(tribe_line)
        out.append("")

    role = data.get("commander_role") or {}
    if role.get("roles"):
        out.append(
            f"**Commander role:** {' + '.join(role['roles'])} — the 99 must supply: "
            + "; ".join(s.split(":")[0] for s in role.get("supplies") or []) + "."
        )
        out.append("")

    clusters = _sorted_clusters(data)
    if clusters:
        wants = set(data.get("commander_wants") or [])
        parts = []
        for name, count in clusters[:8]:
            parts.append(f"{name} {count}{'*' if name in wants else ''}")
        out.append(" · ".join(parts))
        out.append("")
        out.append(r"_\* the commander's own text asks for this._")
        out.append("")

    strain = data.get("castability") or []
    if strain:
        out.append("**Hardest to cast:**")
        out.append("")
        for entry in strain[:4]:
            note = " — sole reason that requirement is high" if entry.get("sole_driver") else ""
            out.append(f"- {entry['name']} `{entry['mana_cost']}` — {entry['reasons'][0]}{note}")
        out.append("")

    over = data.get("oversupplied") or []
    if over:
        parts = []
        for e in over[:4]:
            label = f"{e['category']} {e['count']} (want ~{e['target_high']}"
            label += ", even doubled for the commander)" if e.get("commander_core") else ")"
            parts.append(label)
        out.append("**Oversupplied:** " + ", ".join(parts))
        out.append("")

    out.append(f"_{data.get('note', '')}_")
    out.append("")
    return "\n".join(out)


def _legality_section(data: dict[str, Any]) -> str:
    out = ["## Legality", ""]
    if not data.get("checked"):
        for warning in data.get("warnings", []):
            out.append(f"- {warning}")
        out.append("")
        return "\n".join(out)

    if data["legal"]:
        out.append(f"Legal: {data['total_cards']} cards, singleton, colour identity clean.")
    else:
        out.append("**This deck is not legal as built.**")
        out.append("")
        for error in data["errors"]:
            out.append(f"- {error}")
    for warning in data.get("warnings", []):
        out.append(f"- Note: {warning}")
    out.append("")
    return "\n".join(out)


def _mana_section(data: dict[str, Any]) -> str:
    out = ["## Mana", ""]
    lands = f"**Lands:** {data['land_count']}"
    if data.get("modal_lands"):
        lands += (
            f" (+{data['modal_lands']} modal spell-lands = "
            f"{data['effective_lands']} effective)"
        )
    out.append(f"{lands} · suggested ~{data['recommended_lands']}")
    out.append("")
    if data.get("land_finding"):
        out.append(f"> {data['land_finding']}")
        out.append("")

    if data["colors"]:
        out.append("| Colour | Pips | Heaviest | Sources | Lands | Need |")
        out.append("|---|---:|---:|---:|---:|---:|")
        for entry in data["colors"]:
            need = entry["recommended_sources"] or "—"
            peak = entry["heaviest_requirement"]
            out.append(
                f"| {entry['name']} | {entry['pips']} | {peak} | {entry['total_sources']} "
                f"| {entry['land_sources']} | {need} |"
            )
        out.append("")
        out.append(
            "_Heaviest is the most pips of that colour any single card asks for; "
            "Need is how many sources that card wants to be castable on curve._"
        )
        out.append("")

    for finding in data.get("findings", []):
        out.append(f"- {finding['message']}")
    if data.get("findings"):
        out.append("")

    out.append(f"_{data['note']}_")
    out.append("")
    return "\n".join(out)


def _curve_section(data: dict[str, Any]) -> str:
    out = ["## Curve", ""]
    out.append(f"**Average mana value:** {data['average_mana_value']} (nonland)")
    out.append("")
    histogram = data["histogram"]
    scale = max((v for v in histogram.values()), default=1)
    out.append("```")
    for mv in range(8):
        count = histogram.get(str(mv), 0)
        label = "7+" if mv == 7 else str(mv)
        out.append(f"{label:>2} | {_bar(count, scale):<20} {count}")
    out.append("```")
    out.append("")

    types = data.get("types") or {}
    if types:
        out.append(" · ".join(f"{name} {count}" for name, count in types.items()))
        out.append("")

    for finding in data.get("findings", []):
        out.append(f"- {finding}")
    if data.get("findings"):
        out.append("")
    return "\n".join(out)


def _roles_section(data: dict[str, Any]) -> str:
    out = ["## Roles", ""]
    tag_counts = data.get("tag_counts") or {}
    if tag_counts:
        out.append("| Role | Tags | Oracle text | Typical |")
        out.append("|---|---:|---:|---:|")
    else:
        out.append("| Role | Count | Typical |")
        out.append("|---|---:|---:|")
    targets = data.get("targets") or {}
    for role, count in data["counts"].items():
        target = targets.get(role)
        target_text = f"{target[0]}–{target[1]}" if target else "—"
        if tag_counts:
            tag_text = tag_counts.get(role, "—")
            out.append(f"| {role.title()} | {tag_text} | {count} | {target_text} |")
        else:
            out.append(f"| {role.title()} | {count} | {target_text} |")
    out.append("")

    for finding in data.get("findings", []):
        out.append(f"- {finding['message']}")
    if data.get("findings"):
        out.append("")

    if tag_counts:
        out.append(
            "_Measured two ways — human-curated tags and oracle-text matching. "
            "Where they disagree, the tags are the better signal._"
        )
    else:
        out.append(
            "_Roles come from oracle-text matching, so treat the edges as approximate._"
        )
    out.append("")
    return "\n".join(out)


def _edhrec_section(data: dict[str, Any]) -> str:
    out = ["## Against the EDHREC meta", ""]
    if not data.get("available"):
        out.append(f"No EDHREC comparison available ({data.get('reason', 'unknown')}).")
        out.append("")
        return "\n".join(out)

    if data.get("basis_label"):
        out.append(f"**Basis:** {data['basis_label']}.")
        out.append("")
    sample = data.get("sample_size") or 0
    if sample and data.get("basis") != "theme":
        out.append(f"Compared against ~{sample:,} decks with this commander.")
        out.append("")
    if data.get("small_sample"):
        out.append(
            f"> Small sample ({sample} decks) — every number below is weak evidence."
        )
        out.append("")

    themes = data.get("themes") or []
    if themes:
        parts = [f"{t['name']} ({t['count']})" for t in themes[:6]]
        out.append(f"Build variants EDHREC tracks: {', '.join(parts)}.")
        out.append("")

    similar = data.get("similar") or []
    if similar:
        out.append(f"Closest established commanders: {', '.join(similar[:6])}.")
        out.append("")

    staples = data.get("missing_staples") or []
    if staples:
        out.append("**Staples you're missing** — most decks play these:")
        out.append("")
        for entry in staples:
            out.append(f"- {entry['name']} — in {entry['inclusion']:.0%} of decks")
        out.append("")

    mana_staples = data.get("missing_mana_staples") or []
    if mana_staples:
        names = ", ".join(e["name"] for e in mana_staples[:8])
        out.append(f"_Mana-base staples missing (separate on purpose): {names}._")
        out.append("")

    synergy = data.get("missing_synergy") or []
    if synergy:
        out.append("**High-synergy cards you're missing** — unusually good with this commander:")
        out.append("")
        for entry in synergy:
            out.append(f"- {entry['name']} — synergy +{entry['synergy']:.2f}")
        out.append("")

    off_meta = data.get("off_meta") or []
    if off_meta:
        out.append("**Unusual inclusions** — worth a second look, not automatic cuts:")
        out.append("")
        for entry in off_meta:
            out.append(f"- {entry['name']} — {entry['reason']}")
        out.append("")

    if not staples and not synergy and not off_meta:
        out.append("Nothing notable: the list tracks the meta closely.")
        out.append("")
    return "\n".join(out)


def _combo_section(data: dict[str, Any]) -> str:
    out = ["## Combos", ""]
    if not data.get("available"):
        out.append(f"Combo lookup unavailable ({data.get('reason', 'not run')}).")
        out.append("")
        return "\n".join(out)

    complete = data.get("complete") or []
    near = data.get("near_miss") or []

    if complete:
        out.append("**Already in the deck:**")
        out.append("")
        for combo in complete:
            cards = " + ".join(combo["cards"])
            produces = ", ".join(combo["produces"][:3])
            out.append(f"- {cards} → {produces}")
        out.append("")
    else:
        out.append("No complete combos found among the cards checked.")
        out.append("")

    if near:
        out.append("**One card away:**")
        out.append("")
        for combo in near:
            have = " + ".join(c for c in combo["cards"] if c != combo["missing"])
            produces = ", ".join(combo["produces"][:2])
            out.append(f"- Add **{combo['missing']}** — combos with {have} → {produces}")
        out.append("")

    if data.get("note"):
        out.append(f"_{data['note']}_")
        out.append("")
    return "\n".join(out)


def _bracket_section(data: dict[str, Any]) -> str:
    out = ["## Bracket", ""]
    out.append(f"**Estimate: {data['estimate']} — {data['name']}**")
    out.append("")
    for reason in data.get("reasons", []):
        out.append(f"- {reason}")
    out.append("")

    if data.get("mismatch"):
        out.append(f"> {data['mismatch']}")
        out.append("")

    changers = data.get("game_changers") or []
    if changers:
        out.append(f"Game Changers: {', '.join(changers)}")
        out.append("")

    maybe = data.get("maybeboard") or {}
    if maybe.get("warnings"):
        out.append("**Maybeboard watch:**")
        out.append("")
        for warning in maybe["warnings"]:
            out.append(f"- {warning}")
        out.append("")

    out.append(f"_{data['note']}_")
    out.append("")
    return "\n".join(out)


def _price_section(data: dict[str, Any]) -> str:
    out = ["## Price", ""]
    if not data.get("priced_cards"):
        out.append("No pricing data available (run `mtg cache refresh`).")
        out.append("")
        return "\n".join(out)

    line = f"**Deck total:** ${data['total_usd']:,.2f}"
    if data.get("unpriced_cards"):
        line += f" · {data['unpriced_cards']} cards without a price"
    out.append(line)
    out.append("")
    expensive = data.get("most_expensive") or []
    if expensive:
        out.append("Most expensive:")
        out.append("")
        for entry in expensive:
            out.append(f"- {entry['name']} — ${entry['usd']:,.2f}")
        out.append("")
    return "\n".join(out)


# --- suggestions ----------------------------------------------------------


_GROUP_HEADINGS = (
    (suggest_mod.GROUP_PLAN, "Strengthens the plan"),
    (suggest_mod.GROUP_WEAKNESS, "Fixes a weakness"),
    (suggest_mod.GROUP_META, "Meta staples (optional)"),
)


def render_suggestions(
    deck: Deck,
    result: dict[str, Any],
    built: dict[str, Any] | None = None,
    *,
    budget: float | None = None,
    loose: bool = False,
    max_bracket: int | None = None,
    offline: bool = False,
) -> str:
    """Render the structured suggestions as markdown.

    Conservative by default: only ideas with a deck-internal or
    commander-specific reason appear; popularity-only ideas hide behind
    `--loose`, labelled as exactly that.

    With max_bracket set, adds that would push the deck past it (Game Changers,
    the missing half of a two-card combo, mass land denial) are pulled out into
    their own section instead of being offered as swaps.
    """
    if built is None:
        built = suggest_mod.build(
            deck, result, budget=budget, loose=loose, offline=offline
        )
    out: list[str] = []
    out.append(f"# Suggestions — {deck.name}")
    out.append("")
    out.append(
        "Nothing here is applied automatically. Copy what you agree with into "
        "Archidekt by hand."
    )
    out.append("")

    if budget is not None:
        out.append(f"Filtered to cards at or under ${budget:,.2f}.")
        out.append("")
    if max_bracket is not None:
        out.append(f"Keeping the deck at bracket {max_bracket} or below.")
        out.append("")

    fixes = built["mana_fixes"]
    if fixes:
        out.append("## Fix the mana first")
        out.append("")
        out.append(
            "These cards strain the mana base, but they are part of what the deck "
            "is built around — the fix is sources, not cuts."
        )
        out.append("")
        for fix in fixes:
            line = (
                f"- **+{fix['delta']} {fix['color_name']} source"
                f"{'s' if fix['delta'] > 1 else ''}** — "
                f"{', '.join(fix['driven_by'])} want ~{fix['needed']}, deck has {fix['have']}"
            )
            out.append(line)
            if fix.get("basic_swap"):
                out.append(f"  - {_basic_swap_line(fix['basic_swap'])}")
            if fix.get("swap_candidates"):
                out.append(
                    f"  - lands producing no {fix['color_name']} worth revisiting: "
                    + ", ".join(fix["swap_candidates"])
                )
        out.append("")

    adds = augment_adds_with_bracket_impact(built["adds"], result)
    adds, raises = split_by_bracket(adds, max_bracket)

    out.append("## Consider adding")
    out.append("")
    shown_any = False
    for group, heading in _GROUP_HEADINGS:
        entries = [a for a in adds if a["group"] == group]
        if group == suggest_mod.GROUP_META and not loose:
            continue
        if not entries:
            continue
        shown_any = True
        out.append(f"### {heading}")
        out.append("")
        for entry in entries:
            out.append(f"- {_format_add(entry)}")
        out.append("")
    if not shown_any:
        out.append("- Nothing pressing. The deck covers its bases.")
        out.append("")
    if built["hidden_meta"] and not loose:
        out.append(
            f"_{built['hidden_meta']} popularity-only idea"
            f"{'s' if built['hidden_meta'] > 1 else ''} hidden — `--loose` shows them._"
        )
        out.append("")

    if raises:
        out.append("## Would raise the bracket")
        out.append("")
        out.append(
            f"These came up as adds but would take the deck past bracket {max_bracket}, "
            "so they are listed rather than recommended."
        )
        out.append("")
        for entry in raises:
            out.append(f"- {_format_add(entry)}")
        out.append("")

    cuts = built["cuts"]
    out.append("## Consider cutting")
    out.append("")
    if cuts:
        for entry in cuts:
            out.append(f"- **{entry['name']}** — {entry['why']}  ")
            out.append(f"  _({entry['evidence']})_")
    else:
        out.append(
            "- No confident cuts. Nothing in the deck fails on castability, sits in "
            "an oversupplied cluster, or falls outside what the deck is built around."
        )
        if not loose:
            out.append("- Run with `--loose` to see weaker candidates.")
    out.append("")
    decided = built.get("decided") or []
    if decided:
        groups: dict[str, list[str]] = {}
        for entry in decided:
            groups.setdefault(entry["why"], []).append(entry["name"])
        parts = "; ".join(f"{' · '.join(names)} ({why})" for why, names in groups.items())
        out.append(
            f"_Your call, so not offered again on soft evidence: {parts}. "
            f"To reopen one: `mtg deck intent {deck.slug} --set flexible_cards=+Name`._"
        )
        out.append("")

    raised_names = {r["name"] for r in raises}
    swaps = [s for s in built["swaps"] if s["add"] not in raised_names]
    if swaps:
        out.append("## Paired swaps")
        out.append("")
        out.append("_Each pair does the same job — nothing is matched by position._")
        out.append("")
        for swap in swaps[:8]:
            out.append(f"- {swap['cut']} → {swap['add']} ({swap['shared']})")
        out.append("")

    out.append("---")
    out.append("")
    out.append("_Generated by `mtg deck suggest`._")
    return "\n".join(out) + "\n"


def _basic_swap_line(swap: dict[str, Any]) -> str:
    n = swap["count"]
    return (
        f"free fix: swap {n} {swap['remove']} for {n} {swap['add']} — "
        f"{swap['donor_name']} keeps {swap['donor_left']} sources and needs "
        f"{swap['donor_needed']}"
    )


def _format_add(entry: dict[str, Any]) -> str:
    price = entry.get("price")
    suffix = f" (${price:,.2f})" if price else ""
    line = f"**{entry['name']}**{suffix} — {entry['why']}"
    impact = entry.get("bracket_impact")
    if impact:
        line += f" — **bracket {impact}**: {entry['bracket_reason']}"
    return line


def _bracket_impact_of(name: str, *, combo: dict[str, Any] | None = None) -> tuple[int | None, str]:
    """The lowest bracket a deck can claim once it adds this card.

    Two things are measurable here: whether the card is a Game Changer (from
    the Scryfall cache; unknown when the cache is absent, and unknown is never
    read as "safe"), and whether it completes a two-card combo — bracket 3 by
    definition, or 4 if the combo is mass land denial, unless Spellbook rates
    the combo casual. Extra turns are left alone: one is legal in bracket 2,
    and this tool cannot see chaining.
    """
    from ..sources import scryfall
    from . import bracket as bracket_mod

    if combo is not None:
        if any("mass land denial" in p.lower() for p in combo.get("produces") or []):
            return 4, "completes a mass-land-denial combo"
        if bracket_mod.combo_raises_bracket(combo):
            return 3, "completes a two-card combo"
        return None, ""

    try:
        changer = scryfall.is_game_changer(name)
    except Exception:
        changer = None
    if changer:
        return 3, "a Game Changer"
    return None, ""


def _price_of(name: str) -> float | None:
    """Look up a suggested card's price, tolerating an unreachable Scryfall."""
    from ..sources import scryfall

    try:
        data = scryfall.by_name(name)
    except Exception:
        return None
    if not data:
        return None
    raw = (data.get("prices") or {}).get("usd")
    try:
        return float(raw) if raw else None
    except (TypeError, ValueError):
        return None


def augment_adds_with_bracket_impact(
    adds: list[dict[str, Any]], result: dict[str, Any]
) -> list[dict[str, Any]]:
    """Attach bracket_impact/bracket_reason to each add, without mutating the
    originals — combo-sourced adds are matched back to their combo so mass
    land denial and two-card combos are told apart from a bare Game Changer."""
    combo_by_missing = {
        c["missing"]: c
        for c in (result.get("combos", {}).get("near_miss") or [])
        if c.get("missing")
    }
    augmented = []
    for entry in adds:
        combo = combo_by_missing.get(entry["name"])
        impact, reason = _bracket_impact_of(entry["name"], combo=combo)
        augmented.append({**entry, "bracket_impact": impact, "bracket_reason": reason})
    return augmented


def split_by_bracket(
    adds: list[dict[str, Any]], max_bracket: int | None
) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    """Split bracket-augmented adds into (kept, raises) against a cap.

    With no cap, everything is kept and nothing is raised.
    """
    if max_bracket is None:
        return adds, []
    kept: list[dict[str, Any]] = []
    raised: list[dict[str, Any]] = []
    for entry in adds:
        impact = entry.get("bracket_impact")
        (raised if impact and impact > max_bracket else kept).append(entry)
    return kept, raised


def _build_cuts(
    deck: Deck, result: dict[str, Any], *, loose: bool = False
) -> list[dict[str, Any]]:
    """Kept as the stable entry point; the logic lives in analysis.suggest."""
    return suggest_mod.build_cuts(deck, result, loose=loose)


def render_engine(result: dict[str, Any]) -> str:
    """The deck's engine as a standalone, editable document.

    If the inference is wrong, correcting this file makes the correction stick:
    the tool will not overwrite a version a person has edited.
    """
    data = result.get("engine") or {}
    deck = result.get("deck") or {}
    out = [f"# What {deck.get('name', 'this deck')} is doing", ""]
    out.append(
        "_Inferred from functional card tags. **Edit this file if it's wrong** — "
        "your version wins, and re-analysis will leave it alone._"
    )
    out.append("")

    intent_data = result.get("intent") or {}
    if intent_data.get("archetype") or intent_data.get("win_conditions"):
        out.append("## Declared intent\n")
        if intent_data.get("archetype"):
            out.append(f"**{intent_data['archetype']}**")
        if intent_data.get("win_conditions"):
            out.append(f"Wins by: {'; '.join(intent_data['win_conditions'])}")
        out.append("")

    out.append(f"## Archetype\n\n{data.get('archetype', 'unknown')}")
    out.append("")

    tribe_line = _tribe_line(data)
    if tribe_line:
        out.append(tribe_line)
        out.append("")

    role = data.get("commander_role") or {}
    if role.get("roles"):
        commander = ", ".join(data.get("commander") or []) or "The commander"
        out.append(f"## {commander}'s role\n")
        out.append(f"**{' + '.join(role['roles'])}** — so the 99 must supply:")
        out.append("")
        for supply in role.get("supplies") or []:
            out.append(f"- {supply}")
        out.append("")

    wants = data.get("commander_wants") or []
    if wants:
        commander = ", ".join(data.get("commander") or []) or "The commander"
        out.append(f"## What {commander} asks for\n")
        out.append(", ".join(wants))
        out.append("")

    clusters = _sorted_clusters(data)
    if clusters:
        out.append("## Clusters\n")
        for name, count in clusters:
            marker = " *(commander wants this)*" if name in set(wants) else ""
            out.append(f"- **{name}** — {count} cards{marker}")
        out.append("")

    fixes = data.get("mana_fixes") or []
    if fixes:
        out.append("## Mana-base fixes before cuts\n")
        for fix in fixes:
            out.append(
                f"- +{fix['delta']} {fix['color_name']} source"
                f"{'s' if fix['delta'] > 1 else ''} — "
                f"{', '.join(fix['driven_by'])} want ~{fix['needed']}, deck has {fix['have']}"
            )
            if fix.get("basic_swap"):
                out.append(f"  - {_basic_swap_line(fix['basic_swap'])}")
        out.append("")

    strain = data.get("castability") or []
    if strain:
        out.append("## Hardest to cast\n")
        for entry in strain[:6]:
            note = " — **sole reason that requirement is high**" if entry.get("sole_driver") else ""
            out.append(f"- {entry['name']} `{entry['mana_cost']}`{note}")
            for why in entry["reasons"]:
                out.append(f"  - {why}")
        out.append("")

    wincons = data.get("win_conditions")
    declared_wins = intent_data.get("win_conditions") or []
    if wincons is not None:
        out.append("## How it ends games\n")
        if declared_wins:
            out.append(f"Declared: {'; '.join(declared_wins)}")
            out.append("")
        combos = result.get("combos") or {}
        for combo in combos.get("complete") or []:
            out.append(f"- {' + '.join(combo['cards'])} → {', '.join(combo['produces'][:2])}")
        for entry in wincons[:8]:
            out.append(f"- {entry['name']} — {entry['why']}")
        if not wincons and not (combos.get("complete") or []) and not declared_wins:
            out.append(
                "No clear closer found — the deck may win on incremental damage, "
                "or a finisher is genuinely missing. Worth a look."
            )
        out.append("")

    quadrants = data.get("quadrants") or {}
    if quadrants:
        out.append("## Quadrant coverage\n")
        out.append(
            "_Four game states (EDHREC quadrant theory). A near-zero row is a "
            "plan for that state the deck does not have._\n"
        )
        labels = {
            "developing": "Developing (ramp, draw)",
            "parity": "Breaking parity (removal, sweepers)",
            "winning": "Winning (closers, going wide)",
            "losing": "Behind (protection, recursion)",
        }
        for key, label in labels.items():
            entry = quadrants.get(key) or {}
            parts = " + ".join(f"{c} {n}" for c, n in (entry.get("from") or {}).items())
            out.append(f"- **{label}** — {entry.get('total', 0)} cards{f' ({parts})' if parts else ''}")
        out.append("")

    orphans = data.get("orphans") or []
    if orphans:
        out.append("## Outside every cluster\n")
        out.append(
            "Not automatically bad — the tags may simply not name what these do.\n"
        )
        for name in orphans[:12]:
            out.append(f"- {name}")
        out.append("")

    return "\n".join(out) + "\n"
