"""Render analysis results as markdown.

Written to be read on a phone: short lines, narrow tables, the important
findings at the top. Anyone reading only the first screen should still come
away with the things actually worth changing.
"""

from __future__ import annotations

from typing import Any

from ..model import COLOR_NAMES, Deck
from . import roles as roles_mod

BAR = "█"


def _bar(count: int, scale: int) -> str:
    if scale <= 0:
        return ""
    return BAR * max(0, round(count * 20 / scale))


def render_analysis(result: dict[str, Any]) -> str:
    deck = result["deck"]
    out: list[str] = []

    out.append(f"# {deck['name']}")
    out.append("")
    commanders = ", ".join(deck["commanders"]) or "—"
    identity = "/".join(deck["color_identity"]) or "colourless"
    out.append(f"**Commander:** {commanders}  ")
    out.append(f"**Identity:** {identity} · **Cards:** {deck['total_cards']} · **Format:** {deck['format']}  ")
    out.append(f"**Source:** {deck['url']}")
    out.append("")

    # --- what to look at first ------------------------------------------
    headline = result.get("headline") or []
    out.append("## What stands out")
    out.append("")
    if headline:
        for line in headline:
            out.append(f"- {line}")
    else:
        out.append("- Nothing structural to flag. The deck's shape looks sound.")
    out.append("")

    out.append(_legality_section(result["legality"]))
    out.append(_mana_section(result["mana"]))
    out.append(_curve_section(result["curve"]))
    out.append(_roles_section(result["roles"]))
    out.append(_edhrec_section(result["edhrec"]))
    out.append(_combo_section(result["combos"]))
    out.append(_bracket_section(result["bracket"]))
    out.append(_price_section(result["price"]))

    out.append("---")
    out.append("")
    out.append(
        "_Generated by `mtg deck analyze`. Suggestions are advisory — apply what you "
        "agree with in Archidekt yourself._"
    )
    return "\n".join(out) + "\n"


def _legality_section(data: dict[str, Any]) -> str:
    out = ["## Legality", ""]
    if not data.get("checked"):
        for warning in data.get("warnings", []):
            out.append(f"- {warning}")
        out.append("")
        return "\n".join(out)

    if data["legal"]:
        out.append(f"Legal: {data['total_cards']} cards, singleton, colour identity clean.")
    else:
        out.append("**This deck is not legal as built.**")
        out.append("")
        for error in data["errors"]:
            out.append(f"- {error}")
    for warning in data.get("warnings", []):
        out.append(f"- Note: {warning}")
    out.append("")
    return "\n".join(out)


def _mana_section(data: dict[str, Any]) -> str:
    out = ["## Mana", ""]
    lands = f"**Lands:** {data['land_count']}"
    if data.get("modal_lands"):
        lands += (
            f" (+{data['modal_lands']} modal spell-lands = "
            f"{data['effective_lands']} effective)"
        )
    out.append(f"{lands} · suggested ~{data['recommended_lands']}")
    out.append("")
    if data.get("land_finding"):
        out.append(f"> {data['land_finding']}")
        out.append("")

    if data["colors"]:
        out.append("| Colour | Pips | Heaviest | Sources | Lands | Need |")
        out.append("|---|---:|---:|---:|---:|---:|")
        for entry in data["colors"]:
            need = entry["recommended_sources"] or "—"
            peak = entry["heaviest_requirement"]
            out.append(
                f"| {entry['name']} | {entry['pips']} | {peak} | {entry['total_sources']} "
                f"| {entry['land_sources']} | {need} |"
            )
        out.append("")
        out.append(
            "_Heaviest is the most pips of that colour any single card asks for; "
            "Need is how many sources that card wants to be castable on curve._"
        )
        out.append("")

    for finding in data.get("findings", []):
        out.append(f"- {finding['message']}")
    if data.get("findings"):
        out.append("")

    out.append(f"_{data['note']}_")
    out.append("")
    return "\n".join(out)


def _curve_section(data: dict[str, Any]) -> str:
    out = ["## Curve", ""]
    out.append(f"**Average mana value:** {data['average_mana_value']} (nonland)")
    out.append("")
    histogram = data["histogram"]
    scale = max((v for v in histogram.values()), default=1)
    out.append("```")
    for mv in range(8):
        count = histogram.get(str(mv), 0)
        label = "7+" if mv == 7 else str(mv)
        out.append(f"{label:>2} | {_bar(count, scale):<20} {count}")
    out.append("```")
    out.append("")

    types = data.get("types") or {}
    if types:
        out.append(" · ".join(f"{name} {count}" for name, count in types.items()))
        out.append("")

    for finding in data.get("findings", []):
        out.append(f"- {finding}")
    if data.get("findings"):
        out.append("")
    return "\n".join(out)


def _roles_section(data: dict[str, Any]) -> str:
    out = ["## Roles", ""]
    out.append("| Role | Count | Typical |")
    out.append("|---|---:|---:|")
    targets = data.get("targets") or {}
    for role, count in data["counts"].items():
        target = targets.get(role)
        target_text = f"{target[0]}–{target[1]}" if target else "—"
        out.append(f"| {role.title()} | {count} | {target_text} |")
    out.append("")

    for finding in data.get("findings", []):
        out.append(f"- {finding['message']}")
    if data.get("findings"):
        out.append("")

    out.append(
        "_Roles come from oracle-text matching, so treat the edges as approximate._"
    )
    out.append("")
    return "\n".join(out)


def _edhrec_section(data: dict[str, Any]) -> str:
    out = ["## Against the EDHREC meta", ""]
    if not data.get("available"):
        out.append(f"No EDHREC comparison available ({data.get('reason', 'unknown')}).")
        out.append("")
        return "\n".join(out)

    sample = data.get("sample_size") or 0
    if sample:
        out.append(f"Compared against ~{sample:,} decks with this commander.")
        out.append("")

    staples = data.get("missing_staples") or []
    if staples:
        out.append("**Staples you're missing** — most decks play these:")
        out.append("")
        for entry in staples:
            out.append(f"- {entry['name']} — in {entry['inclusion']:.0%} of decks")
        out.append("")

    synergy = data.get("missing_synergy") or []
    if synergy:
        out.append("**High-synergy cards you're missing** — unusually good with this commander:")
        out.append("")
        for entry in synergy:
            out.append(f"- {entry['name']} — synergy +{entry['synergy']:.2f}")
        out.append("")

    off_meta = data.get("off_meta") or []
    if off_meta:
        out.append("**Unusual inclusions** — worth a second look, not automatic cuts:")
        out.append("")
        for entry in off_meta:
            out.append(f"- {entry['name']} — {entry['reason']}")
        out.append("")

    if not staples and not synergy and not off_meta:
        out.append("Nothing notable: the list tracks the meta closely.")
        out.append("")
    return "\n".join(out)


def _combo_section(data: dict[str, Any]) -> str:
    out = ["## Combos", ""]
    if not data.get("available"):
        out.append(f"Combo lookup unavailable ({data.get('reason', 'not run')}).")
        out.append("")
        return "\n".join(out)

    complete = data.get("complete") or []
    near = data.get("near_miss") or []

    if complete:
        out.append("**Already in the deck:**")
        out.append("")
        for combo in complete:
            cards = " + ".join(combo["cards"])
            produces = ", ".join(combo["produces"][:3])
            out.append(f"- {cards} → {produces}")
        out.append("")
    else:
        out.append("No complete combos found among the cards checked.")
        out.append("")

    if near:
        out.append("**One card away:**")
        out.append("")
        for combo in near:
            have = " + ".join(c for c in combo["cards"] if c != combo["missing"])
            produces = ", ".join(combo["produces"][:2])
            out.append(f"- Add **{combo['missing']}** — combos with {have} → {produces}")
        out.append("")

    if data.get("note"):
        out.append(f"_{data['note']}_")
        out.append("")
    return "\n".join(out)


def _bracket_section(data: dict[str, Any]) -> str:
    out = ["## Bracket", ""]
    out.append(f"**Estimate: {data['estimate']} — {data['name']}**")
    out.append("")
    for reason in data.get("reasons", []):
        out.append(f"- {reason}")
    out.append("")

    if data.get("mismatch"):
        out.append(f"> {data['mismatch']}")
        out.append("")

    changers = data.get("game_changers") or []
    if changers:
        out.append(f"Game Changers: {', '.join(changers)}")
        out.append("")

    out.append(f"_{data['note']}_")
    out.append("")
    return "\n".join(out)


def _price_section(data: dict[str, Any]) -> str:
    out = ["## Price", ""]
    if not data.get("priced_cards"):
        out.append("No pricing data available (run `mtg cache refresh`).")
        out.append("")
        return "\n".join(out)

    line = f"**Deck total:** ${data['total_usd']:,.2f}"
    if data.get("unpriced_cards"):
        line += f" · {data['unpriced_cards']} cards without a price"
    out.append(line)
    out.append("")
    expensive = data.get("most_expensive") or []
    if expensive:
        out.append("Most expensive:")
        out.append("")
        for entry in expensive:
            out.append(f"- {entry['name']} — ${entry['usd']:,.2f}")
        out.append("")
    return "\n".join(out)


# --- suggestions ----------------------------------------------------------


def render_suggestions(deck: Deck, result: dict[str, Any], *, budget: float | None = None) -> str:
    """Turn the analysis into concrete adds and cuts.

    Adds are driven by what the deck lacks, so the same missing staple is a
    stronger suggestion in a deck that is short on ramp than in one that is not.
    """
    out: list[str] = []
    out.append(f"# Suggestions — {deck.name}")
    out.append("")
    out.append(
        "Nothing here is applied automatically. Copy what you agree with into "
        "Archidekt by hand."
    )
    out.append("")

    adds = _build_adds(deck, result, budget=budget)
    cuts = _build_cuts(deck, result)

    if budget is not None:
        out.append(f"Filtered to cards at or under ${budget:,.2f}.")
        out.append("")

    out.append("## Consider adding")
    out.append("")
    if adds:
        for entry in adds:
            price = entry.get("price")
            suffix = f" (${price:,.2f})" if price else ""
            out.append(f"- **{entry['name']}**{suffix} — {entry['why']}")
    else:
        out.append("- Nothing pressing. The deck covers its bases.")
    out.append("")

    out.append("## Consider cutting")
    out.append("")
    if cuts:
        for entry in cuts:
            out.append(f"- **{entry['name']}** — {entry['why']}")
    else:
        out.append("- No obvious cuts. Any change here is a preference call.")
    out.append("")

    if adds and cuts:
        out.append("## Paired swaps")
        out.append("")
        for add, cut in zip(adds[:8], cuts[:8]):
            out.append(f"- {cut['name']} → {add['name']}")
        out.append("")

    out.append("---")
    out.append("")
    out.append("_Generated by `mtg deck suggest`._")
    return "\n".join(out) + "\n"


def _price_of(name: str) -> float | None:
    """Look up a suggested card's price, tolerating an unreachable Scryfall."""
    from ..sources import scryfall

    try:
        data = scryfall.by_name(name)
    except Exception:
        return None
    if not data:
        return None
    raw = (data.get("prices") or {}).get("usd")
    try:
        return float(raw) if raw else None
    except (TypeError, ValueError):
        return None


def _build_adds(
    deck: Deck, result: dict[str, Any], *, budget: float | None
) -> list[dict[str, Any]]:
    adds: list[dict[str, Any]] = []
    seen: set[str] = set()

    # Combos one card away are the most concrete change available.
    for combo in (result["combos"].get("near_miss") or [])[:5]:
        missing = combo.get("missing")
        if not missing or missing.lower() in seen:
            continue
        price = _price_of(missing)
        if budget is not None and price is not None and price > budget:
            continue
        seen.add(missing.lower())
        produces = ", ".join(combo["produces"][:2])
        adds.append(
            {
                "name": missing,
                "price": price,
                "why": f"completes a combo with {' + '.join(c for c in combo['cards'] if c != missing)} → {produces}",
            }
        )

    # Then whatever the role analysis says the deck is short on.
    short_roles = {
        f["role"] for f in result["roles"].get("findings", []) if f["verdict"] == "low"
    }
    edhrec = result["edhrec"]
    candidates = (edhrec.get("missing_staples") or []) + (edhrec.get("missing_synergy") or [])

    if short_roles:
        adds.append(
            {
                "name": f"More {', '.join(sorted(short_roles))}",
                "why": "the role counts above are below the usual range — prioritise these slots",
            }
        )

    for entry in candidates:
        name = entry["name"]
        if name.lower() in seen:
            continue
        price = _price_of(name)
        if budget is not None and price is not None and price > budget:
            continue
        seen.add(name.lower())
        if entry.get("inclusion"):
            why = f"played in {entry['inclusion']:.0%} of decks with this commander"
        else:
            why = f"high synergy (+{entry.get('synergy', 0):.2f}) with this commander"
        adds.append({"name": name, "price": price, "why": why})
        if len(adds) >= 15:
            break

    return adds


def _build_cuts(deck: Deck, result: dict[str, Any]) -> list[dict[str, str]]:
    cuts: list[dict[str, str]] = []
    seen: set[str] = set()

    # Cards outside the commander's identity are not a suggestion, they are a
    # requirement — the deck is illegal until they go.
    identity = set(deck.color_identity())
    for card in deck.cards:
        if card.is_commander:
            continue
        outside = set(card.color_identity) - identity
        if outside:
            seen.add(card.name.lower())
            cuts.append(
                {
                    "name": card.name,
                    "why": f"illegal — {'/'.join(sorted(outside))} is outside your colour identity",
                }
            )

    for entry in result["edhrec"].get("off_meta") or []:
        if entry["name"].lower() in seen:
            continue
        seen.add(entry["name"].lower())
        cuts.append({"name": entry["name"], "why": entry["reason"]})
        if len(cuts) >= 15:
            break

    # If the deck is over-weighted in a role, say which cards make up the excess.
    for finding in result["roles"].get("findings", []):
        if finding["verdict"] != "high":
            continue
        role = finding["role"]
        members = result["roles"]["by_role"].get(role) or []
        for name in members:
            if name.lower() in seen:
                continue
            seen.add(name.lower())
            cuts.append(
                {"name": name, "why": f"deck runs {finding['count']} {role}, above the usual range"}
            )
            break

    return cuts
